name: fashion_nova_clone
description: A Flutter clone of the Fashion Nova e-commerce website

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  google_fonts: ^4.0.4
  shared_preferences: ^2.2.1
  intl: ^0.18.1
  flutter_screenutil: ^5.8.4
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/